# Generated by Django 4.0.4 on 2022-05-16 11:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Organisation',
            new_name='organisation',
        ),
        migrations.AddField(
            model_name='role',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
